"""
V7: Turn the merged, ratio'd multi-year dataset into one readable
Markdown report - the thing you'd actually upload/send.

Also writes a companion CSV (raw numbers, easy to open in Excel/Sheets)
and a JSON (everything, including page numbers + source lines for every
single extracted value, for verification).
"""

import csv
import json


METRIC_LABELS = {
    "revenue": "Revenue",
    "gross_income": "Gross Income (bank: interest + fee income)",
    "net_interest_income": "Net Interest Income (bank)",
    "gross_profit": "Gross Profit",
    "operating_profit": "Operating Profit",
    "profit_before_tax": "Profit Before Tax",
    "net_profit": "Net Profit",
    "eps": "EPS (Rs.)",
    "total_assets": "Total Assets",
    "total_liabilities": "Total Liabilities",
    "total_equity": "Total Equity",
    "cash_and_equivalents": "Cash & Equivalents",
    "total_debt": "Total Debt (borrowings, best-effort — see note)",
    "operating_cash_flow": "Operating Cash Flow",
    "dividend_paid": "Dividend Paid",
}

RATIO_LABELS = {
    "net_profit_margin_pct": "Net Profit Margin (%)",
    "roe_pct": "ROE (%)",
    "roa_pct": "ROA (%)",
    "debt_to_equity": "Debt / Equity",
    "liabilities_to_equity": "Liabilities / Equity",
    "revenue_growth_pct": "Revenue Growth (%)",
    "net_profit_growth_pct": "Net Profit Growth (%)",
    "eps_growth_pct": "EPS Growth (%)",
}


def _fmt(v, decimals=0):
    if v is None:
        return "—"
    if decimals:
        return f"{v:,.{decimals}f}"
    return f"{v:,.0f}"


def build_markdown_report(company_name: str, records: list) -> str:
    years = [r["year"] for r in records]
    lines = []
    lines.append(f"# {company_name} — Financial Summary ({years[0]}–{years[-1]})")
    lines.append("")
    lines.append("_Generated by a deterministic extraction pipeline from the company's own "
                  "annual report PDF(s). Every figure below is traceable to a source page — "
                  "see the accompanying JSON file for exact page numbers and source lines. "
                  "Figures flagged **derived** or **summed** should be spot-checked manually._")
    lines.append("")

    # units note
    units = {r.get("_extractions", {}).get("revenue", {}).get("unit") for r in records}
    units.discard(None)
    if units:
        lines.append(f"**Unit(s) found:** {', '.join(sorted(units))}")
        lines.append("")

    # --- Core financials table ---
    lines.append("## 5-Year Financials")
    lines.append("")
    header = "| Metric | " + " | ".join(str(y) for y in years) + " |"
    sep = "|---|" + "---|" * len(years)
    lines.append(header)
    lines.append(sep)
    for key, label in METRIC_LABELS.items():
        row_vals = []
        any_present = False
        for r in records:
            v = r.get(key)
            if v is not None:
                any_present = True
            decimals = 2 if key == "eps" else 0
            row_vals.append(_fmt(v, decimals))
        if any_present:
            lines.append(f"| {label} | " + " | ".join(row_vals) + " |")
    lines.append("")

    # --- Ratios table ---
    lines.append("## Ratios")
    lines.append("")
    lines.append(header)
    lines.append(sep)
    for key, label in RATIO_LABELS.items():
        row_vals = []
        any_present = False
        for r in records:
            v = r.get("_ratios", {}).get(key)
            if v is not None:
                any_present = True
            row_vals.append(_fmt(v, 2) if v is not None else "—")
        if any_present:
            lines.append(f"| {label} | " + " | ".join(row_vals) + " |")
    lines.append("")

    # --- Verification flags ---
    lines.append("## Needs Manual Verification")
    lines.append("")
    flagged = []
    for r in records:
        for key, ext in r.get("_extractions", {}).items():
            if ext["method"] in ("summed", "derived"):
                flagged.append((r["year"], METRIC_LABELS.get(key, key), ext))
    if flagged:
        for year, label, ext in flagged:
            lines.append(f"- **{year} — {label}** ({ext['method']}, page {ext['page']}): "
                         f"{ext['notes'] or 'check source line'}")
            lines.append(f"  - source: `{ext['source_line'][:150]}`")
    else:
        lines.append("_None — every figure above was matched directly from a labeled line "
                      "in the financial statements._")
    lines.append("")

    # --- Source pages per year ---
    lines.append("## Source Pages (for spot-checking)")
    lines.append("")
    for r in records:
        pages = sorted({ext["page"] for ext in r.get("_extractions", {}).values() if ext["page"] is not None})
        lines.append(f"- **{r['year']}** (`{r.get('source_pdf', '?')}`): pages {pages}")
    lines.append("")

    return "\n".join(lines)


def write_csv(records: list, path: str):
    all_keys = list(METRIC_LABELS.keys())
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["year"] + all_keys)
        for r in records:
            w.writerow([r["year"]] + [r.get(k) for k in all_keys])


def write_json(records: list, path: str):
    clean = []
    for r in records:
        clean.append({k: v for k, v in r.items()})
    with open(path, "w") as f:
        json.dump(clean, f, indent=2, default=str)
